---
- hosts: all
	remote_user: vagrant
	sudo: yes
	tasks:

	- group:
			name: devops
			state: present
	- name: create devops user with admin priviledges
		user: devops
		comment: "Devops User"
		uid: 2001
		group: devops

	- name: install htop package
		action: apt name=htop state=present update_cache=yes

- hosts: www
	user: vagrant
	sudo: yes
	tasks:
	- name: add official nginx repository
		apt_repository:
			repo: 'deb http://nginx.org/packages/ubuntu/ lucid nginx'
	- name: install nginx web server and ensure its at the latest version
		apt:
			name: nginix
			state: latest
	- name: start nginx service
		service:
			name: nginix
			state: started